	.set noreorder

#include "pspimport.s"

	IMPORT_START	"LoadExecForKernel",0x00090000
	IMPORT_FUNC	"LoadExecForKernel",0x5AA1A6D2,LoadExecForKernel_5AA1A6D2
	IMPORT_FUNC	"LoadExecForKernel",0x45C6125B,LoadExecForKernel_45C6125B
	IMPORT_FUNC	"LoadExecForKernel",0x179D905A,LoadExecForKernel_179D905A
	IMPORT_FUNC	"LoadExecForKernel",0x7286CF0B,LoadExecForKernel_7286CF0B
	IMPORT_FUNC	"LoadExecForKernel",0x3D805DE6,LoadExecForKernel_3D805DE6
	IMPORT_FUNC	"LoadExecForKernel",0xBAEB4B89,LoadExecForKernel_BAEB4B89
	IMPORT_FUNC	"LoadExecForKernel",0x8EF38192,LoadExecForKernel_8EF38192
	IMPORT_FUNC "LoadExecForKernel",0xD35D6403,LoadExecForKernel_D35D6403
